### ISSUE TITLE
Unable to push origin

### ISSUE THREAD

**Issue by bsdrocker** [routedbits/dn42-peers#215]
I'm unable to push my branch upstream. This is the error I'm getting:

`ERROR: Permission to routedbits/dn42-peers.git denied to bsdrocker.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

I believe I am following the instructions in the README, so I'm not sure what the issue is.

**Comment by jvoss** [comment]
Please make sure you fork this repository to your own account.

From there, make changes, commit and push to your own fork. Then you can open a pull request here to propose the changes.
